# Generated by Django 6.0 on 2026-01-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='answers',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='questions',
            new_name='question',
        ),
    ]
