# Generated by Django 6.0 on 2026-01-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_answers_flashcard_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
